---
title: "WFAStats"
author: "Heather Lendway"
date: "7/17/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(jsonlite)
library(xml2)
library(rvest)
library(purrr)
```


```{r get each data table}

# url setup

league <- "wfa"
season <- c("2019")
tier <- "1"
tiers <- c("WFA+I","WFA+II","WFA+III")
weeks <- c("1","2","3")#"4","5","6","7","8","9","10")
teams_div_1 <- c("Fighting+Shockwave","War","Titans",
          "Elite","Impact", "Renegades","Divas")
teams_div_2 <- c("Spartans","MH_Blaze", "Outlaws", "Energy", 
                 "Vixen", "Slam", "Dragons", "Nighthawks", 
                 "Fusion", "Comets", "Dark+Angels", 
                 "Dixie+Blues","Fury", "Wolves", "PY_Phantomz", 
                 "Passion", "Inferno")
teams_div_3 <- c("Zydeco", "Wildcats", "Camo", "Mustangs", 
                 "Power", "IO_Phoenix", "Ravens", "Crusaders",
                 "De+La+Muerte", "Royalty", "Panthers", "Storm",
                 "OR_Hawks", "PX_Phantomz", "Thunderkatz", "Heat",
                 "Trojans", "Lady+Gades", "Trauma", "Threat", 
                 "Blitz", "Wolfpack", "Savages",
                 "Sizzle", "Vanguards", "CN_Hawks", "Waverunners", 
                 "Dynamite", "Tidal+Waves", "Lightning", "Mayhem",
                 "Mizfits", "Knockout", "Anarchy", "Black+Widows",
                 "Smash", "Diamondbacks", "Reign")

teams <- c(teams_div_1,teams_div_2,teams_div_3)


#stats_url <- "http://www.hostedstatistics.com/football/team_stats.asp?league=WFA&season=2018&tier=WFA+II&selected_team=Inferno&selected_week=10"

# for testing
#i = 3

table_data <- NULL
headers <- NULL

#l=1
#i=1
#j=1

for(l in 1:length(season)) {

  print(season[l])
  
  for(j in 1:length(teams)) {
    
    print(teams[j])
    
    for(i in 1:length(weeks)) {
    #for(i in 1:2) {
      print(i)
      # eventually loop on all possibilities, i.e. 2017, all tiers and all weeks
      # "&tier=",tiers[2], -- not needed
      stats_url <- paste0("http://www.hostedstatistics.com/football/team_stats.asp?league=WFA&season=",season[l],"&selected_team=",teams[j],"&selected_week=",weeks[i])
    
      # read page data
      stats_page_results <- read_html(stats_url)
      
      # compile page results
      table_data_temp <- stats_page_results %>% 
        html_nodes("table") %>% 
        html_table(fill=TRUE,header=TRUE) %>%
        keep(~(length(grep("Name",names(.))) == 1)) %>% 
        map(~mutate(.x, week = i,team = teams[j], season = season[l])) %>% 
        map(~mutate_all(.x,as.character))
      
      if(is.null(table_data)||length(table_data) == 0) {
        table_data <- table_data_temp
      } else {
        if(length(table_data_temp) > 0) {
          # would be nice if we could keep col type but would have to manually set
          # for each df.... hmm.
          table_data <- map2(table_data,table_data_temp, bind_rows)
        }
      }
      
      if(is.null(headers)) {
        headers <- stats_page_results %>% 
          html_nodes(".indStatHead") %>%
          html_text() %>% 
          as_tibble()
      }
    
    }
    
  }
  
}

saveRDS(table_data,"div_all_stats_2019.rds")

#data <- readRDS("/Users/heatherlendway/Documents/Code/wfa-statistics/div_2_stats.rds")

# TO DO Do something to add the headers in
# for(k in 1:length(headers)) {
#   table_data <- table_data %>% 
#     map(~mutate(.x,week = i,team = teams[j]))
# }



```

```{r}
# get score historical

# http://www.hostedstatistics.com/football/schedule.asp?league=wfa&year=2013
# http://www.hostedstatistics.com/football/schedule.asp?league=wfa&year=2009

week_results_table <- NULL
header_table <- NULL
years <- 2019  #c(2009,2010,2011,2012,2013,2014,2015,2016,2017,2018)

for(m in 1:length(years)) {
  # m = 2 # for testing
  print(years[m])

  scores_url <- paste0("http://www.hostedstatistics.com/football/schedule.asp?league=wfa&year=",years[m])

  # read page data
  scores_page_results <- read_html(scores_url)
    
  heading_data_temp <- scores_page_results %>% 
    html_nodes(".weekHeading") %>% 
    html_text()
  
  # compile page results
  week_data_temp <- scores_page_results %>% 
    html_nodes(".schduleTableGrid") %>% 
    html_table(fill=TRUE,header=TRUE) %>% 
    map(set_names,c("test1","test2","visitor","visitor_score","test5","test6","test7","home_team","home_team_score","test10")) %>% # error said needed to name all columns
    map(select,3:4,8:9) %>% 
    map2_df(heading_data_temp, ~mutate(.x, week = .y, year = years[m])) 
  
  if(is.null(week_results_table)||length(week_results_table) == 0) {
    week_results_table <- week_data_temp
  } else {
    if(length(week_data_temp) > 0) {
      week_results_table <- bind_rows(week_results_table,week_data_temp)
    }
  }
  
}


saveRDS(week_results_table,"game_score_2019.rds")

```

```{r}
function(x,y) {
  z = x+y
  z2 = z - 1
  paste0(x, " plus ", y, " is ", z, " minus 1 that's ", z2, " quick maths")
}
```
